### ISSUE TITLE
Nome delle variabili

### ISSUE THREAD

**Issue by Wabri** [BugliL/PythonPlayground#2]
questo è quello più bello:

https://github.com/BugliL/PythonPlayground/blob/9f102f7331a86fc8210b0362e46d5fc23a02d38c/optimization_algoritm.py#L12

**Comment by BugliL** [comment]
manca un po' di spiegazione dentro la procedura, ma "a" e "b", in quel caso,  sono gli stessi nomi che sono utilizzati come punti che delimitano intervalli dentro gli algoritmi matematici
